import './globals.css'
import { Inter } from 'next/font/google'
import '../styles/global.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CMS Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className='bg-bg-full-img' lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
