import './globals.css'
import '../styles/global.scss'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CMS Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className='' lang="en">
        <body className={inter.className}>{children}</body>
    </html>
  )
}
